### ISSUE TITLE
multiparty stakeholder development specifications

### ISSUE THREAD

**Issue by jonnydubowsky** [f-o-a-m/cliquebait#1]
Create a cross-platform, multi-blockchain tutorial and rational for using Cliquebait in a collaborative bundle of ETH DEV tooling that follows a variety of customized specifications which have been created through an active governance and consensus process that takes place across multiple blockchain projects, curated registries, lists, hackathons, investment groups, and consortiums. 
The first issue will be to write a general overview and specification to get started, followed by an outreach and onboarding campaign, which will integrate into several Sense Collective and YuMatch development activites and grant submissions.

**Comment by iostat** [comment]
Unfortunately, Cliquebait is intended to be used only in testing scenarios and production applications requiring the strictest centralization and repudiation requirements. You may find [TestRPC](https://github.com/trufflesuite/ganache-cli) more suitable for your use case.
