### ISSUE TITLE
Connection not successful

### ISSUE THREAD

**Issue by ice09** [f-o-a-m/cliquebait#4]
Tried the command 

`docker run --rm -it -p 8545:8545 foamspace/cliquebait:latest`

as described in the manual using Windows 10 and macos Sierra and then accessing with `http://localhost:8545` in remix IDE, but to no avail. Connection is not possible, with locally installed Geth or TestRPC, Ganache it is.
Calling `http://localhost:8545` in the host browser displays an empty site, no 400 Bad Request which should be the expected answer.

**Comment by iostat** [comment]
Hi!

AFAIK, 200 OK is normal for a GET / to Geth. The only 4xx you'd get is a 415 when you don't pass `Content-Type: application/json` to a POST. Even JSON-RPC errors will still be a 200 OK.

Which browser are you using? I know Firefox doesn't like letting pages access localhost addresses, so that may be something to consider.

**Comment by ice09** [comment]
Yes, might be ok, but that was the response of a request against an ok running ganache. For Cliquebait the answer is nothing/200. Browser is Chrome. But that's just guessing, more important is the failed connection by remix (called with HTTP and HTTPS, endpoint is web3-provider localhost:8545, error is 

`Not possible to connect to the Web3 provider. Make sure the provider is running and a connection is open (via IPC or RPC).`

Am only I experiencing this? Can be reproduced on completely different machines macos/win10 with the same behaviour.

**Comment by ice09** [comment]
Yes, that's it! Thanks! As I think for first tests many will try Remix or some other web IDE, I'd strongly suggest putting this as a note on the manual/README.
So it works beautiful now, thanks, will close it.

**Comment by iostat** [comment]
Glad that helped. And good idea about putting that in the README! Will do so!

**Comment by iostat** [comment]
Just a heads up, as of https://github.com/f-o-a-m/cliquebait/commit/cc6401686a01082b8254248a2e2457f58f89e36b the flag is now enabled by default!
