### ISSUE TITLE
Print the private keys to the console when the accounts are generated.

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/cliquebait#8]
Can we print the private keys when the accounts are created, like how truffle does? I'm having to convert keyfiles to get them and it's pretty painful.

**Comment by iostat** [comment]
Geth very deliberately does not support this feature, and so it would require introducing dependencies into the image to enable this behavior. Closest you can do is `docker cp <container_name_or_id>:/cbdata/ethereum/keystore <wherever you want it>/` and run something locally to decrypt the keyfiles
